name: Chu Math Badminton Club
description: Blog for Chu Math Badminton Club.
url: 'https://chumathbadmintonclub.github.io'
baseurl: '/jekyll-video'
email: mathstana@gmail.com
#twitter: https://twitter.com/jekyll-video
youtube: https://www.youtube.com/mathruffian
facebook: https://www.facebook.com/steelroydaniel
#google_analytics: ''

################################################################
################################################################
gems:
  - jekyll-sitemap
sass:
  sass_dir: /assets/_sass
  style: :compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
collections:
  videos:
    output: true
    permalink: /:path/
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
  -
    scope:
      path: ''
      type: videos
    values:
      layout: video